// Descriptive alt text per photo (used by pic() unless an image is marked decorative).
export default {
  'main-house-arcade': { en: 'Arcaded courtyard of the Main House at Es Fangar with a long wooden table', es: 'Patio porticado de la Casa Principal de Es Fangar con una larga mesa de madera', de: 'Arkadenhof des Haupthauses von Es Fangar mit langer Holztafel' },
  'main-house-alcove': { en: 'Stone alcove with cushions in the Main House', es: 'Rincón de piedra con cojines en la Casa Principal', de: 'Steinnische mit Kissen im Haupthaus' },
  'main-house-stairs': { en: 'Ochre courtyard and stone staircase of the Main House', es: 'Patio ocre y escalera de piedra de la Casa Principal', de: 'Ockerfarbener Innenhof mit Steintreppe im Haupthaus' },
  'winery-hall': { en: 'Entrance hall of the Es Fangar Vins winery with its hanging vine leaf sculpture', es: 'Vestíbulo de la bodega Es Fangar Vins con su escultura de hojas de vid', de: 'Eingangshalle der Bodega Es Fangar Vins mit hängender Weinblattskulptur' },
  'winery-tasting-bar': { en: 'Tasting bar and wine shop at the Es Fangar Vins bodega in Felanitx', es: 'Barra de catas y tienda de la bodega Es Fangar Vins en Felanitx', de: 'Verkostungstheke und Weinshop der Bodega Es Fangar Vins in Felanitx' },
  'winery-foudres-table': { en: 'Tasting table with Es Fangar wines among the large oak vats of the bodega', es: 'Mesa de catas con vinos de Es Fangar entre los grandes tinos de roble de la bodega', de: 'Verkostungstisch mit Weinen von Es Fangar zwischen den großen Eichenbottichen der Bodega' },
  'winery-tasting-bottles': { en: 'Tasting table of the bodega set with Es Fangar wines, ready for guests', es: 'Mesa de catas de la bodega preparada con vinos de Es Fangar, lista para los invitados', de: 'Verkostungstisch der Bodega mit Weinen von Es Fangar, bereit für die Gäste' },
  'main-house-terrace': { en: 'Long table on a terrace of the Main House among olive trees and bougainvillea', es: 'Mesa larga en una terraza de la Casa Principal entre olivos y buganvillas', de: 'Lange Tafel auf einer Terrasse des Haupthauses zwischen Olivenbäumen und Bougainvillea' },
  'estate-vineyard-valley': { en: 'Vineyards of Es Fangar in the valley, with the hills of Mallorca behind', es: 'Viñedos de Es Fangar en el valle, con las colinas de Mallorca al fondo', de: 'Weinberge von Es Fangar im Tal, dahinter die Hügel Mallorcas' },
  'winery-barrel-hall': { en: 'Rows of oak barrels in the barrel hall of the bodega', es: 'Hileras de barricas de roble en la sala de barricas de la bodega', de: 'Reihen von Eichenfässern im Fasskeller der Bodega' },
  'winery-shop-counter': { en: 'Counter of the Es Fangar Vins bodega with the wine shelves', es: 'Mostrador de la bodega Es Fangar Vins con las estanterías de vino', de: 'Theke der Bodega Es Fangar Vins mit den Weinregalen' },
  'winery-bottle-wall': { en: 'Wall of Es Fangar bottles in the wine library', es: 'Pared de botellas de Es Fangar en la vinoteca', de: 'Flaschenwand mit Weinen von Es Fangar in der Vinothek' },
  'house-garden-aerial': { en: 'One of the houses of the estate in its garden among the pines', es: 'Una de las casas de la finca en su jardín entre pinos', de: 'Eines der Häuser des Guts in seinem Garten zwischen Pinien' },
  'equestrian-indoor-arena': { en: 'Indoor riding arena of Es Fangar under a wooden roof', es: 'Picadero cubierto de Es Fangar bajo un techo de madera', de: 'Reithalle von Es Fangar unter einem Holzdach' },
  'winery-tasting-table': { en: 'Tasting table with Es Fangar wines under a hanging installation of metal leaves', es: 'Mesa de catas con vinos de Es Fangar bajo una instalación colgante de hojas metálicas', de: 'Verkostungstisch mit Weinen von Es Fangar unter einer hängenden Installation aus Metallblättern' },
  'winery-tasting-room': { en: 'Private tasting room surrounded by the wine library', es: 'Sala de catas privada rodeada por la vinoteca', de: 'Privater Verkostungsraum inmitten der Vinothek' },
  'winery-tanks': { en: 'Stainless steel fermentation tanks in the gravity winery', es: 'Depósitos de fermentación de acero inoxidable en la bodega por gravedad', de: 'Gärtanks aus Edelstahl in der Schwerkraftkellerei' },
  'winery-gravity-hall': { en: 'Production hall with the overhead crane rails of the gravity method', es: 'Sala de elaboración con los raíles de la grúa del método gravedad', de: 'Produktionshalle mit den Deckenschienen der Schwerkraftmethode' },
  'winery-barrels': { en: 'Barrel cellar with Es Fangar wines on an olive wood table', es: 'Sala de barricas con los vinos de Es Fangar sobre una mesa de olivo', de: 'Fasskeller mit Weinen von Es Fangar auf einem Olivenholztisch' },
  'arabic-house-interior': { en: 'Moorish style living room of the Arabic House', es: 'Salón de estilo morisco de la Casa Árabe', de: 'Wohnzimmer im maurischen Stil im Arabischen Haus' },
  'equestrian-aerial': { en: 'Aerial view of the equestrian facilities among stone pines', es: 'Vista aérea de las instalaciones ecuestres entre pinos', de: 'Luftaufnahme der Reitanlage zwischen Pinien' },
  'equestrian-track': { en: 'Arenas, stables and the racetrack of Es Fangar from above', es: 'Pistas, cuadras y circuito de Es Fangar desde el aire', de: 'Reitplätze, Stallungen und Rennbahn von Es Fangar aus der Luft' },
  'landscape-coast': { en: 'Southeast Mallorca from above, with Porto Colom and the sea', es: 'El sureste de Mallorca desde el aire, con Porto Colom y el mar', de: 'Der Südosten Mallorcas aus der Luft mit Porto Colom und dem Meer' },
  'gardens-aerial': { en: 'Formal gardens and pool of the Main House at dusk', es: 'Jardines formales y piscina de la Casa Principal al atardecer', de: 'Formale Gärten und Pool des Haupthauses in der Abenddämmerung' },
  'reserve-dusk': { en: 'Hills covered in pine of the nature reserve at sunset', es: 'Colinas de pinar de la reserva natural al atardecer', de: 'Pinienbewachsene Hügel des Naturreservats bei Sonnenuntergang' },
  'estate-sunset': { en: 'Sunset over the vineyards and the Serra de Tramuntana from Es Fangar', es: 'Atardecer sobre los viñedos y la Serra de Tramuntana desde Es Fangar', de: 'Sonnenuntergang über den Weinbergen und der Serra de Tramuntana von Es Fangar aus' },
  'main-house-dusk-wide': { en: 'The Main House, gardens and pool lit at dusk', es: 'La Casa Principal, los jardines y la piscina iluminados al anochecer', de: 'Haupthaus, Gärten und Pool beleuchtet in der Dämmerung' },
  'main-house-topdown': { en: 'View from above of the knot garden and cloister of the Main House', es: 'Vista cenital del jardín y el claustro de la Casa Principal', de: 'Draufsicht auf den Knotengarten und den Kreuzgang des Haupthauses' },
  'main-house-night': { en: 'The Main House of Es Fangar lit at night', es: 'La Casa Principal de Es Fangar iluminada de noche', de: 'Das Haupthaus von Es Fangar bei Nacht' },
  'main-house-night-front': { en: 'Main House façade and garden axis at night', es: 'Fachada de la Casa Principal y eje del jardín de noche', de: 'Fassade des Haupthauses und Gartenachse bei Nacht' },
  'main-house-pool-night': { en: 'Bisazza mosaic pool and the Main House at night', es: 'Piscina de mosaico Bisazza y la Casa Principal de noche', de: 'Mosaikpool von Bisazza und Haupthaus bei Nacht' },
  'main-house-sunset': { en: 'Es Fangar estate at sunset with the Main House and gardens', es: 'La finca Es Fangar al atardecer con la Casa Principal y los jardines', de: 'Das Gut Es Fangar bei Sonnenuntergang mit Haupthaus und Gärten' },
  'vines-closeup': { en: 'Rows of organic vines in summer', es: 'Hileras de viñas ecológicas en verano', de: 'Reihen biologischer Reben im Sommer' },
  'vineyard-manor': { en: 'Organic vineyard with the Main House on the hill behind', es: 'Viñedo ecológico con la Casa Principal en la colina', de: 'Bioweinberg mit dem Haupthaus auf dem Hügel' },
  'vineyard-wide': { en: 'Organic vineyards of Es Fangar under a blue sky', es: 'Viñedos ecológicos de Es Fangar bajo el cielo azul', de: 'Bioweinberge von Es Fangar unter blauem Himmel' },
  'main-house-lawn': { en: 'Lawn, pool and the Main House among trees', es: 'Césped, piscina y la Casa Principal entre árboles', de: 'Rasen, Pool und Haupthaus zwischen Bäumen' },
  'main-house-pool': { en: 'Mosaic pool and steps lined with palms leading to the Main House', es: 'Piscina de mosaico y escalinata de palmeras hacia la Casa Principal', de: 'Mosaikpool und palmengesäumte Treppe zum Haupthaus' },
  'arabic-house-pool': { en: 'Private pool of the Arabic House with sun loungers', es: 'Piscina privada de la Casa Árabe con tumbonas', de: 'Privater Pool des Arabischen Hauses mit Sonnenliegen' },
  'arabic-house-lounge': { en: 'Living room with fireplace in the Arabic House', es: 'Salón con chimenea en la Casa Árabe', de: 'Wohnzimmer mit Kamin im Arabischen Haus' },
  'arabic-house-aerial': { en: 'The Arabic House and its pool from above', es: 'La Casa Árabe y su piscina desde el aire', de: 'Das Arabische Haus mit Pool aus der Luft' },
  'arabic-house-garden': { en: 'Palm garden of the Arabic House', es: 'Jardín de palmeras de la Casa Árabe', de: 'Palmengarten des Arabischen Hauses' },
  'mallorcan-house-garden': { en: 'The Mallorcan House with its garden and pergola', es: 'La Casa Mallorquina con su jardín y pérgola', de: 'Das Mallorquinische Haus mit Garten und Pergola' },
  'mallorcan-house-living': { en: 'Living room with stone fireplace in the Mallorcan House', es: 'Salón con chimenea de piedra en la Casa Mallorquina', de: 'Wohnzimmer mit Steinkamin im Mallorquinischen Haus' },
  'mallorcan-house-aerial': { en: 'The Mallorcan House and private pool from above', es: 'La Casa Mallorquina y su piscina privada desde el aire', de: 'Das Mallorquinische Haus mit privatem Pool aus der Luft' },
  'mallorcan-house-pergola': { en: 'Pergola covered in vines of the Mallorcan House', es: 'Pérgola cubierta de parra de la Casa Mallorquina', de: 'Weinberankte Pergola des Mallorquinischen Hauses' },
  'lodge-pool': { en: 'The pool of The Lodge, with the house behind', es: 'La piscina de The Lodge, con la casa al fondo', de: 'Der Pool der Lodge, dahinter das Haus' },
  'lodge-living': { en: 'Dining area and kitchen with stone walls in The Lodge', es: 'Comedor y cocina con paredes de piedra en The Lodge', de: 'Essbereich und Küche mit Steinwänden in der Lodge' },
  'lodge-terrace': { en: 'Covered terrace of The Lodge', es: 'Terraza cubierta de The Lodge', de: 'Überdachte Terrasse der Lodge' },
  'box-12': { en: 'Twelve bottles of TwentyTwelve Pink, offer of 12 for 90 €', es: 'Doce botellas de TwentyTwelve Pink, oferta 12 por 90 €', de: 'Zwölf Flaschen TwentyTwelve Pink, Angebot 12 für 90 €' },
  'box-12-white': { en: 'Twelve bottles of TwentyTwelve White, offer of 12 for 90 €', es: 'Doce botellas de TwentyTwelve White, oferta 12 por 90 €', de: 'Zwölf Flaschen TwentyTwelve White, Angebot 12 für 90 €' },
  'arabic-house-exterior': { en: 'The Arabic House with its crenellated walls and lawn', es: 'La Casa Árabe con sus muros almenados y el césped', de: 'Das Arabische Haus mit Zinnenmauern und Rasen' },
  'arabic-house-kitchen': { en: 'Kitchen of the Arabic House', es: 'Cocina de la Casa Árabe', de: 'Küche des Arabischen Hauses' },
  'arabic-house-bedroom': { en: 'Bedroom with draped bed in the Arabic House', es: 'Dormitorio con dosel en la Casa Árabe', de: 'Schlafzimmer mit Himmelbett im Arabischen Haus' },
  'arabic-house-bedroom-2': { en: 'Second bedroom of the Arabic House', es: 'Segundo dormitorio de la Casa Árabe', de: 'Zweites Schlafzimmer des Arabischen Hauses' },
  'arabic-house-bath': { en: 'Bathroom with turquoise tiles in the Arabic House', es: 'Baño con azulejos turquesa en la Casa Árabe', de: 'Bad mit türkisfarbenen Fliesen im Arabischen Haus' },
  'arabic-house-pool-aerial': { en: 'The pool and pavilions of the Arabic House from above', es: 'La piscina y los pabellones de la Casa Árabe desde el aire', de: 'Pool und Pavillons des Arabischen Hauses aus der Luft' },
  'mallorcan-house-dining': { en: 'Open plan living and dining area of the Mallorcan House', es: 'Salón comedor abierto de la Casa Mallorquina', de: 'Offener Wohnbereich und Essbereich des Mallorquinischen Hauses' },
  'mallorcan-house-kitchen': { en: 'Kitchen of the Mallorcan House', es: 'Cocina de la Casa Mallorquina', de: 'Küche des Mallorquinischen Hauses' },
  'mallorcan-house-bedroom': { en: 'Bedroom opening onto the garden in the Mallorcan House', es: 'Dormitorio con salida al jardín en la Casa Mallorquina', de: 'Schlafzimmer mit Zugang zum Garten im Mallorquinischen Haus' },
  'mallorcan-house-bedroom-2': { en: 'Second bedroom of the Mallorcan House', es: 'Segundo dormitorio de la Casa Mallorquina', de: 'Zweites Schlafzimmer des Mallorquinischen Hauses' },
  'mallorcan-house-bath': { en: 'Bathroom of the Mallorcan House', es: 'Baño de la Casa Mallorquina', de: 'Bad des Mallorquinischen Hauses' },
  'mallorcan-house-garden-2': { en: 'Shaded garden terrace of the Mallorcan House', es: 'Terraza a la sombra en el jardín de la Casa Mallorquina', de: 'Schattige Gartenterrasse des Mallorquinischen Hauses' },
  'lodge-aerial': { en: 'The Lodge in the forest, seen from above', es: 'The Lodge en el bosque, vista desde el aire', de: 'Die Lodge im Wald aus der Luft' },
  'lodge-forest': { en: 'The Lodge on a wooded hillside', es: 'The Lodge en una ladera boscosa', de: 'Die Lodge an einem bewaldeten Hang' },
  'arabic-house-living': { en: 'Moorish living room with long sofas in the Arabic House', es: 'Salón morisco con largos sofás en la Casa Árabe', de: 'Maurisches Wohnzimmer mit langen Sofas im Arabischen Haus' },
  'arabic-house-hall': { en: 'Hall with carved doors in the Arabic House', es: 'Recibidor con puertas talladas en la Casa Árabe', de: 'Diele mit geschnitzten Türen im Arabischen Haus' },
  'mallorcan-house-exterior': { en: 'The Mallorcan House among pine trees', es: 'La Casa Mallorquina entre pinos', de: 'Das Mallorquinische Haus zwischen Pinien' },
  'mallorcan-house-view': { en: 'View over the countryside from the Mallorcan House', es: 'Vistas al campo desde la Casa Mallorquina', de: 'Blick über das Land vom Mallorquinischen Haus' },
  'lodge-stone-room': { en: 'Living room with stone walls and terracotta floor in The Lodge', es: 'Salón con paredes de piedra y suelo de barro en The Lodge', de: 'Wohnraum mit Steinwänden und Terrakottaboden in der Lodge' },
  'lodge-sitting': { en: 'Sitting area with leather armchairs in The Lodge', es: 'Zona de estar con sillones de cuero en The Lodge', de: 'Sitzecke mit Ledersesseln in der Lodge' },
  'lodge-kitchen': { en: 'Rustic kitchen and dining table of The Lodge', es: 'Cocina rústica y mesa de comedor de The Lodge', de: 'Rustikale Küche und Esstisch der Lodge' },
  'lodge-bedroom': { en: 'Bedroom with canopy bed in The Lodge', es: 'Dormitorio con cama con dosel en The Lodge', de: 'Schlafzimmer mit Himmelbett in der Lodge' },
  'lodge-bedroom-2': { en: 'Second bedroom of The Lodge', es: 'Segundo dormitorio de The Lodge', de: 'Zweites Schlafzimmer der Lodge' },
  'lodge-bath': { en: 'Bathroom with freestanding bathtub in The Lodge', es: 'Baño con bañera exenta en The Lodge', de: 'Bad mit freistehender Badewanne in der Lodge' },
  'lodge-kitchen': { en: 'Kitchen and dining table of The Lodge under a beamed cane ceiling, with ceramic plates on the walls', es: 'Cocina y mesa de comedor de The Lodge bajo un techo de vigas y cañizo, con platos de cerámica en las paredes', de: 'Küche und Esstisch von The Lodge unter einer Decke aus Balken und Schilf, mit Keramiktellern an den Wänden' },
  'lodge-pool-2': { en: 'Small pool of The Lodge among pines and oleanders', es: 'Pequeña piscina de The Lodge entre pinos y adelfas', de: 'Kleiner Pool der Lodge zwischen Pinien und Oleander' },
};
