"""Copy the prototype's static files into the Shopify theme and generate the
snippets that depend on them.

    py tools/export-shopify-assets.py ../es-fangar-shopify

- assets/: WebP photos (all widths), share images (og-*.jpg), hero videos, icons
- snippets/logo-*.liquid: the SVG logos, inline, coloured with currentColor
- snippets/asset-image-meta.liquid: widths and size of each bundled photo
Theme assets must live in a flat folder, so og/home.jpg becomes og-home.jpg.
"""
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'src'
ASSETS = SRC / 'assets'
# bottle, box and scene photos come from the Shopify products themselves
PRODUCT_PHOTOS = ('bottle-', 'box-', 'scene-')


def used_in_theme(theme):
    """Photo names referenced by the theme's templates, sections and snippets (only these are copied)."""
    text = ''.join(f.read_text(encoding='utf-8', errors='ignore')
                   for d in ('templates', 'sections', 'snippets', 'layout') for f in (Path(theme) / d).rglob('*')
                   if f.is_file() and f.name != 'asset-image-meta.liquid')
    return lambda name: name in text


def main(theme):
    theme = Path(theme)
    used = used_in_theme(theme)
    out = theme / 'assets'
    # photos the theme no longer uses
    for f in out.glob('*.webp'):
        if f.name.startswith('cutout-'):  # product cut-outs, made by tools/product-cutouts.py
            continue
        if not used(f.name.rsplit('-', 1)[0]):
            f.unlink()
    out.mkdir(parents=True, exist_ok=True)
    n = 0
    for f in sorted((ASSETS / 'img').glob('*.webp')):
        if not f.name.startswith(PRODUCT_PHOTOS) and used(f.name.rsplit('-', 1)[0]):
            shutil.copy2(f, out / f.name); n += 1
    for f in sorted((ASSETS / 'img' / 'og').glob('*.jpg')):
        shutil.copy2(f, out / f'og-{f.name}'); n += 1
    shutil.copy2(ASSETS / 'img' / 'logo-es-fangar.png', out / 'logo-es-fangar.png')
    # fonts are not copied: the theme uses the brand fonts (Playfair Display, Poppins) in its own assets
    for f in (ASSETS / 'video').glob('*.mp4'):
        shutil.copy2(f, out / f.name); n += 1
    for name in ['favicon-32.png', 'apple-touch-icon.png', 'icon-192.png', 'icon-512.png']:
        shutil.copy2(ASSETS / name, out / name); n += 1
    emblem = (ROOT / 'source' / 'logo' / 'emblem.svg').read_text(encoding='utf-8').strip()
    (out / 'favicon.svg').write_text(emblem.replace('fill="currentColor"', 'fill="#592C82"'), encoding='utf-8')
    print(f'copied {n} files to {out}')

    snippets = theme / 'snippets'
    snippets.mkdir(exist_ok=True)
    for src, name in [('es-fangar-logo', 'logo-full'), ('emblem', 'logo-emblem'), ('wordmark', 'logo-wordmark'), ('vins-logo', 'logo-vins')]:
        svg = (ROOT / 'source' / 'logo' / f'{src}.svg').read_text(encoding='utf-8').strip()
        svg = svg.replace('<svg ', '<svg class="{{ class }}" aria-hidden="true" focusable="false" ', 1)
        (snippets / f'{name}.liquid').write_text(
            '{%- comment -%} Generated from source/logo/' + src + '.svg by tools/export-shopify-assets.py. '
            'Accepts: class {%- endcomment -%}\n' + svg + '\n', encoding='utf-8')

    images = json.loads((SRC / 'content' / 'images.json').read_text(encoding='utf-8'))
    lines = ['{%- comment -%}',
             '  Generated by tools/export-shopify-assets.py: "widths|width|height|focus" of a bundled photo (focus: optional horizontal focal point in %)',
             '  (assets/<name>-<width>.webp). Accepts: name',
             '{%- endcomment -%}',
             '{%- case name -%}']
    for name, m in sorted(images.items()):
        if name.startswith(PRODUCT_PHOTOS) or not used(name):
            continue
        h = round(m['h'] * (m['widths'][-1] / m['w']))
        focus = f"|{m['focus']}" if 'focus' in m else ''   # horizontal focal point (%), e.g. to keep a table in view
        lines.append(f"  {{%- when '{name}' -%}}{','.join(map(str, m['widths']))}|{m['widths'][-1]}|{h}{focus}")
    lines.append('{%- endcase -%}')
    (snippets / 'asset-image-meta.liquid').write_text('\n'.join(lines) + '\n', encoding='utf-8', newline='\n')
    # widths left over from an earlier version of a photo
    for f in out.glob('*.webp'):
        name, _, w = f.stem.rpartition('-')
        if name in images and w.isdigit() and int(w) not in images[name]['widths']:
            f.unlink()
    print('wrote snippets')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else '../es-fangar-shopify')
